### PR TITLE
Ignore trial items that are asking for what we cannot provide

### PR DESCRIPTION
**Pull request by libraryaddict**

### CODE REVIEW

**Comment by phulin** [comment]
I don't think this logic is right, but I need to think about this more and reread the original code.

**Comment by libraryaddict** [comment]
> This isn't right. A trial item that is later in the list could end up freeing the space needed.

What about removing the capacity check here?

https://github.com/loathers/libram/blob/main/src/diet/index.ts#L649

**Comment by gausie** [comment]
@phulin any more thoughts? i know this is busy season

**Comment by phulin** [comment]
I think the suggestion above is fine - the filtering should happen later.

**Comment by gausie** [comment]
Ok. @libraryaddict can you sort that out?

**Pull request closed without merging**
