### PR TITLE
add clan.haveInRupus function

### PR DESCRIPTION
**Pull request by Tokoeka**
add fucntion to check if an individual piece of clan  rumpus room furniture is in the rumpus room

### CODE REVIEW

**Review by horrible-little-slime — COMMENTED** [review]
I can see why this is in `Clan.ts`, but I'm not sure it actually belongs here if it isn't using Clan-hopping support. We have some analogous functions for the campground in `lib`, it may be better to put it there.

The big thing is you have essentially made this an instance method of the `Clan` class that doesn't ever use any attributes of the instance or features of the class itself.

**Comment by gausie** [comment]
Agreed, move to lib. Mafia is already caching this so there's no need to add to the class.

**Comment by gausie** [comment]
@Tokoeka I'll mark this as stale in one week unless indicated otherwise

**Comment by gausie** [comment]
It's been 2 months! Closing

**Pull request closed without merging**
